name: Continuous Integration
on: [push]
jobs:
  build-test-node-envs-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Name ${{ matrix.node }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node}}
      - run: yarn install
      - run: yarn test
      - run: yarn build
