name: CI Test
on: [push]
jobs:
  Test-Multiple-node-envs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Running on node version ${{matrix.node}}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Lint Code
        run: yarn lint
      - name: Test App
        run: yarn test
      - name: Build App
        run: yarn build
