name: UAT Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build-deploy-UAT:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}
        id: extract_branch

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:uat

      - name: Deploy
        run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }}/${{steps.extract_branch.outputs.branch}}
