name: User Acceptance Test
on:
  pull_request:
    branches:
      - master
jobs:
  Build_Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      SOURCE_DIR: './build/'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PATHS: '/*'
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - uses: actions/checkout@v1

      - name: Deploying on Node ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Get branch name
        id: vars
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:uat

      - name: AWS Deploy
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks

        env:
          DEST_DIR: ${{steps.vars.outputs.branch}}
